Merged revisions 6760,6771,6778,6782,6784,6792-6793,6797-6798,6802-6804,6808-6809,6817-6819,6823 via svnmerge from http://sesat.no/svn/sesat-kernel/branches/2.17
........
  r6760 | ssmiweve | 2008-08-13 10:20:13 +0200 (Wed, 13 Aug 2008) | 1 line
  
  http://permalink.gmane.org/gmane.comp.java.sesat.kernel.devel/155
........
  r6771 | ssmiweve | 2008-08-19 17:21:16 +0200 (Tue, 19 Aug 2008) | 5 lines
  
  undo r6760
   svn merge -r6760:6759 http://sesat.no/svn/sesat-kernel/branches/2.17 .
  
  Didn't work.
........
  r6778 | ssmiweve | 2008-08-19 19:37:52 +0200 (Tue, 19 Aug 2008) | 3 lines
  
  remove restrictions on redeploying sesat on test environments.
  restriction remains for gamma and production
........
  r6782 | sshafroi | 2008-08-20 12:49:01 +0200 (Wed, 20 Aug 2008) | 1 line
  
  Make it a warning, since this will take 5 sec if it fails, and you will not see anything with default logs.
........
  r6784 | sshafroi | 2008-08-20 15:55:36 +0200 (Wed, 20 Aug 2008) | 4 lines
  
  Regexp only matched tags with longer names then 1 character. It will now match tags like <b>.
  
  See: Issue SKER4947:  (StringChopper will not handle cdata) 
........
  r6792 | ssmiweve | 2008-08-26 23:55:54 +0200 (Tue, 26 Aug 2008) | 5 lines
  
  https://jira.sesam.no/jira/browse/SVERIGE-1349
   live collection was passed through from one SearchDataObject to the next :-(
   a better copy constructors implemented in BasicResultList,
    and CopySearchRunHandler handles copying what the copy constructor cannot.
........
  r6793 | sshafroi | 2008-08-29 10:03:46 +0200 (Fri, 29 Aug 2008) | 1 line
  
  Revert 6782, change warn back to debug.
........
  r6797 | ssmiweve | 2008-08-30 09:35:35 +0200 (Sat, 30 Aug 2008) | 9 lines
  
  
  > java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
  >         at java.util.ArrayList.RangeCheck(ArrayList.java:547)
  >         at java.util.ArrayList.get(ArrayList.java:322)
  >         at java.util.Collections$UnmodifiableList.get(Collections.java:1154)
  >         at no.sesat.search.run.handler.FederatorRunHandler.insertResult(FederatorRunHandler.java:90)
  >         at no.sesat.search.run.handler.FederatorRunHandler.handleRunningQuery(FederatorRunHandler.java:63)
........
  r6798 | ssmiweve | 2008-09-08 11:06:35 +0200 (Mon, 08 Sep 2008) | 1 line
  
  Issue SKER4938:  (OverturePPCSearchCommand must support serverUrl parameter) 
........
  r6802 | ssmiweve | 2008-09-11 14:37:43 +0200 (Thu, 11 Sep 2008) | 2 lines
  
  cleanup our usage of jboss ejb3 client libraries.
   only those from http://sesat.no/maven2/org/jboss/ should be used.
........
  r6803 | ssenrogn | 2008-09-15 08:47:07 +0200 (Mon, 15 Sep 2008) | 1 line
  
  Added Eclipse files to ignore list.
........
  r6804 | ssenrogn | 2008-09-15 08:47:12 +0200 (Mon, 15 Sep 2008) | 1 line
  
  Added Eclipse files to ignore list.
........
  r6808 | ssenrogn | 2008-09-16 09:22:50 +0200 (Tue, 16 Sep 2008) | 1 line
  
  SEARCH-4987 - rename of news case facade.
........
  r6809 | ssenrogn | 2008-09-16 09:24:00 +0200 (Tue, 16 Sep 2008) | 1 line
  
  SEARCH-4987 - new version of newsadmin-services, cleanup of jboss deps.
........
  r6817 | ssmiweve | 2008-09-16 23:05:32 +0200 (Tue, 16 Sep 2008) | 2 lines
  
  fix mistake made in r6802
........
  r6818 | ssmiweve | 2008-09-16 23:56:01 +0200 (Tue, 16 Sep 2008) | 2 lines
  
  switch sesam.com back to idp command
........
  r6819 | ssmiweve | 2008-09-16 23:57:26 +0200 (Tue, 16 Sep 2008) | 2 lines
  
  Issue SKER5004:  (Create option to disable the automatic rewrite of <multi-word query> to (<multi-word query>) when there are zero hits across all verticals) 
........
  r6823 | ssmiweve | 2008-09-18 11:43:03 +0200 (Thu, 18 Sep 2008) | 1 line
  
  SEARCH-5022- Correct sitemap erros etc. appearing in the Google webmaster tool
........


git-svn-id: http://sesat.no/svn/sesat-kernel/trunk@6827 cdc3010f-a60b-0410-91f3-d90f869209c8