Merged revisions 6592-6645 via svnmerge from http://sesat.no/svn/sesat-kernel/branches/2.17
........
  r6599 | ssmiweve | 2008-05-13 08:30:08 +0200 (Tue, 13 May 2008) | 1 line
  
  query string being printed out in utf encoded format
........
  r6611 | sshafroi | 2008-05-14 09:19:27 +0200 (Wed, 14 May 2008) | 5 lines
  
  Move the sesat-mojo deploy out of the include-fast and development profile. You will now have to add sesat-mojo:deploy or do a 'mvn install' in the skins to get the needed files copied into your webapps directory.
  
  The searchModesSchemaGenerator has been moved out of the development profile and will always bee executed.
........
  r6613 | ssmiweve | 2008-05-14 10:53:32 +0200 (Wed, 14 May 2008) | 2 lines
  
  javadoc
........
  r6614 | ssmiweve | 2008-05-14 10:54:09 +0200 (Wed, 14 May 2008) | 2 lines
  
  Issue SKER4742:  (VelocityTemplateTest.VelocityLoader.getUrl(..) doesn't handle parent sites)
........
  r6619 | ssenrogn | 2008-05-14 13:39:51 +0200 (Wed, 14 May 2008) | 4 lines
  
  RESOLVED - SKER4745:
  Support for different rank profiles on single and multiple term searches
  
  http://sesat.no/scarab/issues/id/SKER4745
........
  r6626 | ssmiweve | 2008-05-15 14:06:05 +0200 (Thu, 15 May 2008) | 10 lines
  
  fix relating to comment in SKER4656 from AndersB:
  java.lang.AssertionError: Parent must exist for all Sites except the DEFAULT
    at no.sesat.search.site.Site.<init>(Site.java:189)
    at no.sesat.search.site.Site.valueOf(Site.java:297)
    at no.sesat.search.site.Site.<init>(Site.java:184)
    at no.sesat.search.site.Site.valueOf(Site.java:297)
    at no.sesat.search.site.Site.<init>(Site.java:184)
    at no.sesat.search.site.Site.valueOf(Site.java:297)
    at no.sesat.search.http.filters.SiteLocatorFilter.getSite(SiteLocatorFilter.java:329)
    at no.sesat.search.http.filters.SiteLocatorFilter.doBeforeProcessing(SiteLocatorFilter.java:440)
........
  r6627 | ssmiweve | 2008-05-19 11:29:24 +0200 (Mon, 19 May 2008) | 1 line
  
  SEARCH-4643 - stackoverflow on sch-http05
........
  r6630 | ssmiweve | 2008-05-19 16:50:34 +0200 (Mon, 19 May 2008) | 1 line
  
  SEARCH-4642 - Lockup on sch-http02 immediately after restart
........
  r6631 | ssenrogn | 2008-05-22 09:07:06 +0200 (Thu, 22 May 2008) | 5 lines
  
  RESOLVED - SEARCH-4733:
  NewsClusteringESPFastCommand: Could not convert result java.lang.NullPointerException.
  Added extra null-pointer-check.
  
  https://jira.sesam.no/jira/browse/SEARCH-4733
........
  r6642 | ssmiweve | 2008-05-27 18:08:37 +0200 (Tue, 27 May 2008) | 2 lines
  
  cleanup around how frontpage is handled. redirect from empty search from default tab to / removed since urlrewrite.xml clobbered that behaviour. part of workings on SEARCH-809 // SKER4747
........
  r6644 | ssmiweve | 2008-05-28 13:59:02 +0200 (Wed, 28 May 2008) | 1 line
  
  SKER-4747- Issue SKER4747:  (Missing query parameter gives illegal fast esp queries)
........


git-svn-id: http://sesat.no/svn/sesat-kernel/trunk@6646 cdc3010f-a60b-0410-91f3-d90f869209c8